dbt_metrics_app:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account-json
      project: dbt-metrics-dw
      dataset: analytics
      job_execution_timeout_seconds: 300
      threads: 4

      keyfile_json:
        type: "{{ env_var(gcp_service_account_type) }}"
        project_id: "{{ env_var(gcp_service_account_project_id) }}"
        private_key_id: "{{ env_var(gcp_service_account_private_key_id) }}"
        private_key: "{{ env_var(gcp_service_account_private_key) }}"
        client_email: "{{ env_var(gcp_service_account_client_email) }}"
        client_id: "{{ env_var(gcp_service_account_client_id) }}"
        auth_uri: "{{ env_var(gcp_service_account_auth_uri) }}"
        token_uri: "{{ env_var(gcp_service_account_token_uri) }}"
        auth_provider_x509_cert_url: "{{ env_var(gcp_service_account_auth_provider_x509_cert_url) }}"
        client_x509_cert_url: "{{ env_var(gcp_service_account_client_x509_cert_url) }}"