dbt_metrics_app:
  outputs:
    dev:
      dataset: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/michaeldouglas/bq-dbt-metrics-app-serviceaccount.json
      location: US
      method: service-account
      priority: interactive
      project: dbt-metrics-dw
      threads: 4
      type: bigquery
  target: dev
