dbt_metrics_app:
  outputs:
    dev:
      dataset: analytics
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('SA_KEY_PATH') }}"
      location: US
      method: service-account
      priority: interactive
      project: dbt-metrics-dw
      threads: 4
      type: bigquery
  target: dev
